framework:
  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_headers:
    - x-forwarded-for
    - x-forwarded-host
    - x-forwarded-proto
    - x-forwarded-port
    - x-forwarded-prefix
    - forwarded
  trusted_hosts:
    - '%env(TRUSTED_HOSTS)%'
